 const quotes = [
"Dream big and dare to fail.",
"Stay hungry, stay foolish.",
"Action is the foundational key to success.",
"Believe you can and you're halfway there.",
"Turn your wounds into wisdom.",
"Everything you can imagine is real.",
"Simplicity is the ultimate sophistication.",
"Whatever you are, be a good one.",
"Happiness depends upon ourselves.",
"Do what you can with what you have.",
"Make each day your masterpiece.",
"Wherever you go, go with all your heart.",
"Success is not final; failure is not fatal.",
"Be yourself; everyone else is already taken.",
"Impossible is just an opinion.",
"Start where you are. Use what you have.",
"If opportunity doesn’t knock, build a door.",
"Stay foolish to stay sane.",
"What we think, we become.",
"The purpose of our lives is to be happy.",
"Don’t wait. The time will never be just right.",
"Everything has beauty, but not everyone sees it.",
"Light tomorrow with today.",
"Great things never come from comfort zones.",
"Dream it. Wish it. Do it.",
"Little things make big days.",
"Don’t stop when you’re tired. Stop when you’re done.",
"Work hard in silence, let success make the noise.",
"Wake up with determination. Go to bed with satisfaction.",
"Do something today that your future self will thank you for.",
"Push yourself, because no one else will do it for you.",
"Success doesn’t just find you.",
"The harder you work, the luckier you get.",
"Dream bigger. Do bigger.",
"Don’t limit your challenges. Challenge your limits.",
"It’s going to be hard, but hard does not mean impossible.",
"Sometimes later becomes never. Do it now.",
"Great things take time.",
"Your only limit is your mind.",
"Be stronger than your excuses.",
"Doubt kills more dreams than failure ever will.",
"Stay positive, work hard, make it happen.",
"Don’t watch the clock; do what it does. Keep going.",
"The secret of getting ahead is getting started.",
"Opportunities don’t happen. You create them.",
"Success is what comes after you stop making excuses.",
"Discipline is choosing between what you want now and what you want most.",
"Focus on the goal, not the obstacles.",
"Success is the sum of small efforts repeated daily.",
"Fall seven times, stand up eight.",
"Quality is not an act, it is a habit.",
"Everything you’ve ever wanted is on the other side of fear.",
"Hard work beats talent when talent doesn’t work hard.",
"Your passion is waiting for your courage to catch up.",
"Magic happens when you don’t give up.",
"Try again. Fail again. Fail better.",
"Turn your dreams into plans.",
"Be so good they can’t ignore you.",
"If you want it, work for it.",
"Success starts with self-discipline.",
"Make today count.",
"Keep going. Everything you need will come to you.",
"Stay focused and never give up.",
"The best way out is always through.",
"Small steps every day.",
"You are capable of amazing things.",
"Prove them wrong.",
"Make it happen.",
"Stay humble. Hustle hard.",
"Risk is better than regret.",
"Success is built on consistency.",
"Your vibe attracts your tribe.",
"Be fearless in the pursuit of what sets your soul on fire.",
"Don’t quit your daydream.",
"Work until your idols become your rivals.",
"Strive for progress, not perfection.",
"Every moment is a fresh beginning.",
"Be the change you wish to see.",
"Done is better than perfect.",
"Create your own sunshine.",
"Nothing will work unless you do.",
"Don’t be busy. Be productive.",
"Success is a journey, not a destination.",
"Make yourself proud.",
"Stay patient and trust your journey.",
"Start now. Not tomorrow.",
"Believe in your infinite potential.",
"One day or day one. You decide.",
"Focus on what matters.",
"Progress over perfection.",
"You miss 100% of the shots you don’t take.",
"Energy flows where attention goes.",
"Success loves preparation.",
"Be bold or italic, never regular.",
"Your future needs you.",
"Be unstoppable.",
"Rise and grind.",
"Think big. Act bigger.",
"Chase goals, not people.",
"Never stop learning."
];
function quotes1(){
const id=document.getElementById('root')
const Index=Math.floor(Math.random()*quotes.length);
id.textContent=quotes[Index]};

setInterval(()=>{
quotes1();
},5000)